/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao.quarto;

import br.com.visao.reserva.*;
import br.com.controle.Reserva;
import br.com.controle.Quarto;
import br.com.entidade.ManterQuarto;
import br.com.entidade.ManterReserva;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LuiF
 */
public class CancelarEAlterarQuarto extends javax.swing.JFrame {
    
    Quarto q = new Quarto();
    /**
     * Creates new form CancelarEAlterarReserva
     */
    public CancelarEAlterarQuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBalterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jBimprimir = new javax.swing.JButton();
        jCtipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLvalor = new javax.swing.JLabel();
        jCqtdCamas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTquartos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBalterar.setText("Alterar Dados");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Deletar ou Alterar Quarto");

        jBcancelar.setText("Deletar Quarto");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBimprimir.setText("Mostrar Quartos");
        jBimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirActionPerformed(evt);
            }
        });

        jCtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "normal", "master", "deluxe" }));
        jCtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipo do Quarto:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade de Camas:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Valor do Quarto:");

        jLvalor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLvalor.setText("0.00");

        jCqtdCamas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4" }));
        jCqtdCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCqtdCamasActionPerformed(evt);
            }
        });

        jTquartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo", "Quantidade de Camas", "Valor", "Reservado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTquartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTquartosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTquartos);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Código:");

        jTcodigo.setColumns(4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBimprimir)
                        .addGap(144, 144, 144)
                        .addComponent(jBcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jBalterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLvalor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCqtdCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jCqtdCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLvalor))
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancelar)
                    .addComponent(jBimprimir)
                    .addComponent(jBalterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        q.setTipo(jCtipo.getSelectedItem().toString());
        q.setQtdCama(Integer.valueOf(jCqtdCamas.getSelectedItem().toString()));
        q.setSoma(Double.valueOf(jLvalor.getText()));
        q.setCodigo(Integer.valueOf(jTcodigo.getText()));
        ManterQuarto dao = new ManterQuarto();
        try {
            dao.AtualizarQuarto(q);
        } catch (Exception ex) {
            Logger.getLogger(CancelarEAlterarQuarto.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        if(q.isReservado() == false) {
            q.setCodigo(Integer.valueOf(jTcodigo.getText()));
            ManterQuarto dao = new ManterQuarto();
            try {
                dao.deletarQuarto(q);
            } catch (Exception ex) {
                Logger.getLogger(CancelarEAlterarQuarto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Quarto reservado, não é possível deletar");
        }
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirActionPerformed
        // TODO add your handling code here:
        try {
            Quarto q = new Quarto();
            ManterQuarto dao = new ManterQuarto();
            DefaultTableModel quarto = (DefaultTableModel) jTquartos.getModel();
            quarto.setRowCount(0);
            {
                ArrayList<Quarto> quartos = dao.PesquisarQuarto();
                for (int i = 0; i < quartos.size(); i++) {
                    q = quartos.get(i);
                    quarto.addRow(new Object[]{q.getCodigo(), q.getTipo(), q.getQtdCama(), q.getSoma(), q.isReservado()});
                    System.out.println("q" + q.getCodigo() + q.getTipo() + q.getQtdCama() + q.getSoma() + q.isReservado());
                }
            }
        } catch (Exception e) {
            System.out.println("Erro " + e.getMessage());
        }
    }//GEN-LAST:event_jBimprimirActionPerformed

    private void jCtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoActionPerformed
        // TODO add your handling code here:

        if (null != jCtipo.getSelectedItem().toString()) switch (jCtipo.getSelectedItem().toString()) {
            case " " -> q.setValorTipo(0.0);
            case "normal" -> q.setValorTipo(50.00);
            case "master" -> q.setValorTipo(143.00);
            case "deluxe" -> q.setValorTipo(183.20);
        }
        jLvalor.setText(String.valueOf(q.somaValor()));
    }//GEN-LAST:event_jCtipoActionPerformed

    private void jCqtdCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCqtdCamasActionPerformed
        // TODO add your handling code here:

        if (null != jCqtdCamas.getSelectedItem().toString()) switch (jCqtdCamas.getSelectedItem().toString()) {
            case " " -> q.setValorCama(0.0);
            case "1" -> q.setValorCama(20.00);
            case "2" -> q.setValorCama(45.00);
            case "3" -> q.setValorCama(70.00);
            case "4" -> q.setValorCama(95.00);
        }
        jLvalor.setText(String.valueOf(q.somaValor()));
    }//GEN-LAST:event_jCqtdCamasActionPerformed

    private void jTquartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTquartosMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTquartos.getModel();
        
        String tblCodigo = tblModel.getValueAt(jTquartos.getSelectedRow(), 0).toString();
        String tblTipo = tblModel.getValueAt(jTquartos.getSelectedRow(), 1).toString();
        String tblQtdCamas = tblModel.getValueAt(jTquartos.getSelectedRow(), 2).toString();
        String tblValor = tblModel.getValueAt(jTquartos.getSelectedRow(), 3).toString();
        
        jTcodigo.setText(tblCodigo);
        jCtipo.setSelectedItem(tblTipo);
        jCqtdCamas.setSelectedItem(tblQtdCamas);
        jLvalor.setText(tblValor);
    }//GEN-LAST:event_jTquartosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarEAlterarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarEAlterarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarEAlterarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarEAlterarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarEAlterarQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBimprimir;
    private javax.swing.JComboBox<String> jCqtdCamas;
    private javax.swing.JComboBox<String> jCtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLvalor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTable jTquartos;
    // End of variables declaration//GEN-END:variables
}
